[package]
name = "hacking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "first"
path = "src/first.rs"

[[bin]]
name = "char_array"
path = "src/char_array.rs"

